import {
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Church,
  ClipboardCheck,
  ClipboardList,
  FileText,
  Files,
  GraduationCap,
  HandCoins,
  Heart,
  History,
  Home,
  Landmark,
  LayoutDashboard,
  LineChart,
  PiggyBank,
  Receipt,
  Settings,
  Target,
  Users,
  Wallet,
} from "lucide-react";

import type { NavGroup } from "@/types/navigation";

export const navigationGroups: NavGroup[] = [
  {
    id: "main",
    label: "Main",
    items: [
      {
        id: "home",
        label: "Home",
        href: "/",
        icon: Home,
        roles: [
          "ORG_ADMIN",
          "FINANCE_MANAGER",
          "ACCOUNTANT",
          "FUNDRAISING_MANAGER",
          "PROGRAM_MANAGER",
          "STAFF",
          "AUDITOR",
          "VIEW_ONLY",
        ],
        priority: "primary",
      },
      {
        id: "executive-dashboard",
        label: "Executive overview",
        href: "/dashboard/executive",
        icon: LayoutDashboard,
        roles: ["ORG_ADMIN", "PROGRAM_MANAGER", "STAFF", "VIEW_ONLY", "AUDITOR"],
        priority: "secondary",
      },
      {
        id: "finance-dashboard",
        label: "Finance overview",
        href: "/dashboard/finance",
        icon: Wallet,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "ACCOUNTANT"],
        priority: "secondary",
      },
      {
        id: "fundraising-dashboard",
        label: "Fundraising overview",
        href: "/dashboard/fundraising",
        icon: HandCoins,
        roles: ["ORG_ADMIN", "FUNDRAISING_MANAGER"],
        priority: "secondary",
      },
    ],
  },
  {
    id: "fundraising",
    label: "Fundraising",
    items: [
      {
        id: "donors",
        label: "Donors",
        href: "/donors",
        icon: Heart,
        roles: ["ORG_ADMIN", "FUNDRAISING_MANAGER", "FINANCE_MANAGER", "STAFF"],
        priority: "primary",
      },
      {
        id: "campaigns",
        label: "Campaigns",
        href: "/campaigns",
        icon: Target,
        roles: ["ORG_ADMIN", "FUNDRAISING_MANAGER", "STAFF"],
        priority: "primary",
      },
      {
        id: "donations",
        label: "Donations",
        href: "/donations",
        icon: PiggyBank,
        roles: ["ORG_ADMIN", "FUNDRAISING_MANAGER", "FINANCE_MANAGER", "STAFF"],
        priority: "primary",
      },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    items: [
      {
        id: "expenses",
        label: "Expenses",
        href: "/expenses",
        icon: Receipt,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "STAFF"],
        priority: "primary",
      },
      {
        id: "funds",
        label: "Funds",
        href: "/funds",
        icon: Landmark,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "ACCOUNTANT", "STAFF"],
        priority: "primary",
      },
      {
        id: "budgets",
        label: "Budgets",
        href: "/budgets",
        icon: BarChart3,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER"],
        priority: "secondary",
      },
      {
        id: "accounting",
        label: "Accounting",
        href: "/accounting/chart-of-accounts",
        icon: BookOpen,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "ACCOUNTANT"],
        priority: "secondary",
      },
    ],
  },
  {
    id: "workflow",
    label: "Workflow",
    items: [
      {
        id: "approvals",
        label: "Approvals",
        href: "/approvals",
        icon: ClipboardCheck,
        roles: [
          "ORG_ADMIN",
          "FINANCE_MANAGER",
          "FUNDRAISING_MANAGER",
          "PROGRAM_MANAGER",
          "STAFF",
          "ACCOUNTANT",
        ],
        priority: "primary",
      },
      {
        id: "reports",
        label: "Reports",
        href: "/reports",
        icon: LineChart,
        roles: [
          "ORG_ADMIN",
          "FINANCE_MANAGER",
          "FUNDRAISING_MANAGER",
          "ACCOUNTANT",
          "PROGRAM_MANAGER",
          "STAFF",
          "AUDITOR",
          "VIEW_ONLY",
        ],
        priority: "primary",
      },
    ],
  },
  {
    id: "more-communication",
    label: "Communication",
    defaultCollapsed: true,
    items: [
      {
        id: "notifications",
        label: "Notifications",
        href: "/notifications",
        icon: Bell,
        roles: [
          "ORG_ADMIN",
          "FINANCE_MANAGER",
          "FUNDRAISING_MANAGER",
          "PROGRAM_MANAGER",
          "STAFF",
          "ACCOUNTANT",
          "AUDITOR",
          "VIEW_ONLY",
        ],
        priority: "secondary",
      },
      {
        id: "activity",
        label: "Activity",
        href: "/activity",
        icon: History,
        roles: [
          "ORG_ADMIN",
          "FINANCE_MANAGER",
          "FUNDRAISING_MANAGER",
          "PROGRAM_MANAGER",
          "STAFF",
          "ACCOUNTANT",
          "AUDITOR",
          "VIEW_ONLY",
        ],
        priority: "secondary",
      },
      {
        id: "documents",
        label: "Documents",
        href: "/documents",
        icon: Files,
        roles: [
          "ORG_ADMIN",
          "FINANCE_MANAGER",
          "FUNDRAISING_MANAGER",
          "PROGRAM_MANAGER",
          "STAFF",
          "ACCOUNTANT",
          "AUDITOR",
          "VIEW_ONLY",
        ],
        priority: "secondary",
      },
    ],
  },
  {
    id: "programs",
    label: "Programs",
    defaultCollapsed: true,
    items: [
      {
        id: "programs",
        label: "Programs",
        href: "/programs",
        icon: FileText,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "PROGRAM_MANAGER"],
        organizationTypes: ["NGO", "FOUNDATION", "CHARITY", "COMMUNITY_ORGANIZATION", "SCHOOL"],
        priority: "secondary",
      },
      {
        id: "grants",
        label: "Grants",
        href: "/grants",
        icon: FileText,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "PROGRAM_MANAGER"],
        organizationTypes: ["NGO", "FOUNDATION", "CHARITY", "COMMUNITY_ORGANIZATION"],
        priority: "secondary",
      },
      {
        id: "beneficiaries",
        label: "Beneficiaries",
        href: "/beneficiaries",
        icon: Users,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "PROGRAM_MANAGER", "STAFF"],
        organizationTypes: ["NGO", "FOUNDATION", "CHARITY", "COMMUNITY_ORGANIZATION", "SCHOOL"],
        priority: "secondary",
      },
    ],
  },
  {
    id: "verticals",
    label: "Verticals",
    defaultCollapsed: true,
    items: [
      {
        id: "church-ministries",
        label: "Ministries",
        href: "/church/ministries",
        icon: Church,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "STAFF"],
        organizationTypes: ["CHURCH", "RELIGIOUS_INSTITUTION"],
        priority: "secondary",
      },
      {
        id: "church-attendance",
        label: "Attendance",
        href: "/church/attendance",
        icon: ClipboardList,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "STAFF"],
        organizationTypes: ["CHURCH", "RELIGIOUS_INSTITUTION"],
        priority: "secondary",
      },
      {
        id: "school",
        label: "Sponsorships",
        href: "/school/sponsorships",
        icon: GraduationCap,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "PROGRAM_MANAGER", "STAFF"],
        organizationTypes: ["SCHOOL"],
        priority: "secondary",
      },
    ],
  },
  {
    id: "administration",
    label: "Administration",
    items: [
      {
        id: "users",
        label: "Users",
        href: "/admin/users",
        icon: Users,
        roles: ["ORG_ADMIN"],
        priority: "primary",
      },
      {
        id: "settings",
        label: "Settings",
        href: "/admin/settings",
        icon: Settings,
        roles: ["ORG_ADMIN"],
        priority: "secondary",
      },
    ],
  },
  {
    id: "developer",
    label: "Developer",
    defaultCollapsed: true,
    items: [
      {
        id: "components",
        label: "Components",
        href: "/dev/components",
        icon: Building2,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "FUNDRAISING_MANAGER", "PROGRAM_MANAGER", "STAFF", "ACCOUNTANT"],
        priority: "secondary",
      },
      {
        id: "reference-list",
        label: "Reference list",
        href: "/dev/reference-list",
        icon: FileText,
        roles: ["ORG_ADMIN", "FINANCE_MANAGER", "FUNDRAISING_MANAGER", "PROGRAM_MANAGER", "STAFF", "ACCOUNTANT"],
        priority: "secondary",
      },
      {
        id: "reference-form",
        label: "Reference form",
        href: "/dev/reference-form",
        icon: FileText,
        roles: ["ORG_ADMIN", "FUNDRAISING_MANAGER", "STAFF"],
        priority: "secondary",
      },
    ],
  },
];
